apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odoo-ingress
  namespace: odoo
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: odoo.esmos.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: odoo
                port:
                  number: 8069
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osticket-ingress
  namespace: osticket
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: helpdesk.esmos.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: osticket
                port:
                  number: 8080
