apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/JarudeC/esmos-healthcare-devsecops-platform.git
    targetRevision: main
    path: kubernetes/odoo

  destination:
    server: https://kubernetes.default.svc
    namespace: odoo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
